# "awi" crate - Licensed under the MIT LICENSE
#  * Copyright (c) 2017-2018  Jeron A. Lau <jeron.lau@plopgrizzly.com>
#                             _        _
#                            /@\——————/@\
# .———  .                   |   o    o   |     .————      .            .
# |   | |  .———   .———   .——.     []     .——.  |      .——    ———: ———: | .   .
# |   | |  |   |  |   |  \   \   <##>   /   /  |      |   |    /    /  | |   |
# |———  |  |   |  |   |   |   ¯        ¯   |   |   -- |   |   /    /   |  \ /
# |     |  |   |  |———    |                |   |    | |   |  /    /    |   |
# |     |   ———   |       |                |    ————  |   | :——— :———  |   |
#                 |        \              /                              __/
#                           ¯————————————¯

[package]
name = "awi"
version = "0.7.0"
authors = [
	"Jeron A. Lau <jeron.lau@plopgrizzly.com>"
]

license = "MIT"
documentation = "https://docs.rs/awi"
homepage = "http://plopgrizzly.com/awi"
repository = "https://github.com/plopgrizzly/awi"

readme = "readme.md"
description = "Create a window and handle it's input."
keywords = ["window", "graphics", "interface", "native", "ffi"]
categories = ["gui", "hardware-support", "os", "rendering"]

exclude = [
	"examples/*", "code_of_conduct.md", "contributing.md", ".gitignore",
	"_config.yml", "issue_template.md", "icon.png", "icon.ico"
]

[dependencies]
afi = "0.5"
afi_docf = "0.0"
stick = "0.4"

# Unix: Runtime Link to xcb,
[target.'cfg(any(target_os = "linux", target_os = "macos", target_os = "freebsd", target_os = "dragonfly", target_os = "bitrig", target_os = "openbsd", target_os = "netbsd"))'.dependencies]
dl_api = "0.1"

# Windows: Compiletime link to winapi
[target.'cfg(target_os="windows")'.dependencies]
winapi = { version = "0.3", features = ["winuser", "libloaderapi", "winerror", "minwindef", "errhandlingapi"] }